### ISSUE TITLE
1.A MINOR ERROR

### ISSUE THREAD

**Issue by HegdeRama** [RitamChakraborty/Cognizant_Early_Engagement#3]
MODIFY COLUMN PHONE_NO INT(10).

**Comment by RitamChakraborty** [comment]
If you are talking about (this)[https://github.com/RitamChakraborty/Cognizant_Early_Engagement/tree/master/Dashboard/Database%20Management/Hands-On/SQL%20Basics%20with%20DML%20and%20DDL%20Statements/Car%20rental%20system%20-%20Create%20Table], then the datatype specified in the description is bigint.

**Comment by HegdeRama** [comment]
For me in description it was mentioned to modify "varchar(10)" to "int(10)".

**Comment by HegdeRama** [comment]
[https://github.com/RitamChakraborty/Cognizant_Early_Engagement/tree/master/Dashboard/Database%20Management/Code%20Challenge/Code%20Challenge%202%20-%20RDBMS%20DDL%20%26%20DML/Hostel-Insert%20Student%20Records%20set2](url)


I am talking about this program.

**Comment by HegdeRama** [comment]
And I am talking about [this](https://github.com/RitamChakraborty/Cognizant_Early_Engagement/tree/master/Dashboard/Database%20Management/Code%20Challenge/Code%20Challenge%202%20-%20RDBMS%20DDL%20%26%20DML/Hostel-Insert%20Student%20Records%20set2).

**Comment by RitamChakraborty** [comment]
Got it. Thanks.
