### ISSUE TITLE
FILE NAME GOT EXCHANGED

### ISSUE THREAD

**Issue by HegdeRama** [RitamChakraborty/Cognizant_Early_Engagement#4]

**Comment by RitamChakraborty** [comment]
Can you be little brief?

**Comment by HegdeRama** [comment]
[Cognizant_Early_Engagement/Dashboard/Database Management/Code Challenge/Code Challenge 2 - RDBMS DDL & DML/Hostel-Insert Student Records set2/
](url) 
Here we have 2 programs,and file name have got exchanged.

**Comment by Advith98** [comment]
https://github.com/RitamChakraborty/Cognizant_Early_Engagement/tree/master/Dashboard/Database%20Management/Code%20Challenge/Code%20Challenge%202%20-%20RDBMS%20DDL%20%26%20DML

Here we have 2 programs,and file name have got exchanged.

**Comment by RitamChakraborty** [comment]
On sql code challenge 2, there are 2 challenges.

**Comment by HegdeRama** [comment]
Yeah. And both file name got exchanged.Check question name and file name
there.

**Comment by RitamChakraborty** [comment]
Got it.
